# Generated by Django 3.0.3 on 2020-02-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicvote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', to='musicvote.Artist'),
        ),
    ]
