# Generated by Django 3.0.3 on 2020-02-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicvote', '0005_auto_20200206_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
