# Generated by Django 3.0.3 on 2020-02-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicvote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['song_title']},
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', to='musicvote.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
