# Generated by Django 3.0.3 on 2020-02-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicvote', '0002_auto_20200205_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
