# Generated by Django 3.0.3 on 2020-02-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicvote', '0004_auto_20200205_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['song_title']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='musicvote.Song'),
        ),
    ]
