# Generated by Django 3.0.3 on 2020-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicvote', '0008_auto_20200210_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(),
        ),
    ]
