# Generated by Django 3.0.3 on 2020-02-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicvote', '0009_auto_20200210_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
